config/routes.rb
CarsonAuto::Application.routes.draw do
  
  root to: 'static_pages#home'
  
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :cars
  resources :users
  resources :ship_addresses
  resources :payment_cards
  resources :carts
  resources :cart_items, only: [:create, :destroy]
  resources :orders
  resources :incoices

  resources :sessions, only: [:new, :create, :destroy]

  match '/addcars', to: 'cars#new'
  
  match '/home', to: 'static_pages#home'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/help', to: 'static_pages#help'

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/edit_user', to: 'users#edit'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/address', to: 'ship_addresses#new'
  match '/ship_address', to: 'ship_addresses#show'
  match '/edit_address', to: 'ship_addresses#edit'
  match '/delete_address', to: 'ship_addresses#destroy'

  match '/new_card', to: 'payment_cards#new'
  match '/credit_card', to: 'payment_cards#show'
  match '/delete_card', to: 'payment_cards#destroy'
  
  match '/add_cart', to: 'carts#create'

  match '/add_cart_item', to: 'cart_items#create'
  match '/show_cart_items', to: 'cart_items#index'
  match '/destroy_cart_item', to: 'cart_items#destroy'
 
  match '/place_order', to: 'orders#create'
  match '/order_history', to: 'orders#show'

  match '/invoice', to: 'invoices#create'

  match '/find_cars', to: 'cars#index'

end

app/controllers/ship_addresses_controller.rb
class ShipAddressesController < ApplicationController

	def index
		@ship_address = ship_addresses.find(current_user)		
	end

	def new
		@ship_address = ShipAddress.new
	end

	def show
		@ship_address = current_user.ship_addresses.find(current_user)
		rescue ActiveRecord::RecordNotFound
				
	end

	def create
		@ship_address = current_user.ship_addresses.build(params[:ship_address])
		if @ship_address.save
		flash[:success] = "Address added!"
		redirect_to(current_user)
		else
		render 'static_pages/home'
		end
	end

	def edit
		@ship_address = ShipAddress.find_by_user_id(current_user)
		rescue ActiveRecord::RecordNotFound
	end

	def update
		@ship_address = ShipAddress.find_by_user_id(current_user)
	    if @ship_address.update_attributes(params[:ship_address])
	      flash[:success] = "Address information updated"
	      redirect_to(ship_address_path)
	      
	    else
	      render 'edit'
	    end		
		
	end

	def destroy
		ShipAddress.find(params[:id]).destroy
		redirect_to(current_user)
	end
end

app/helpers/ship_addresses_helper.rb
module ShipAddressesHelper
	def ship_address
		@ship_address = ShipAddress.find_by_user_id(current_user)
		rescue ActiveRecord::RecordNotFound
	end

	def ship_address?
		!@ship_address.nil?
	end
end

app/views/ship_addresses/create.html.erb
<% provide(:title, 'Addresses') %>
<h3>Your profile </h3>
		<div class="row">
			<div class="span6 offset3">
				<%= form_for(@ship_address) do |f| %>
				<%= render 'shared/error_messages', object: f.object %>
				<%= f.label :region %>
				<%= f.text_field :region %>
				<%= f.label :country %>
				<%= f.country_select :country%>
				<%= f.label :address %>
				<%= f.text_field :address %>
				<%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
				<% end %>
				
			</div>
		</div>

app/views/ship_addresses/edit.html.erb
<% provide(:title, 'Addresses') %>
<h3>Edit Ship Address information </h3>
		<div class="row">
			<div class="span6 offset3">
				<%= form_for(@ship_address) do |f| %>
				<%= render 'shared/error_messages', object: f.object %>
				<%= f.label :region %>
				<%= f.text_field :region %>
				<%= f.label :country %>
				<%= f.country_select :country%>
				<%= f.label :address %>
				<%= f.text_field :address %>
				<%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
				<% end %>
				
			</div>
		</div>

app/views/ship_addresses/index.html.erb
<ul><%=render @ship_addresses  %></ul>

app/views/ship_addresses/new.html.erb
<% provide(:title, 'Addresses') %>

<h3>Add Shipping address </h3>
		<div class="row">
			<div class="span6 offset3">
				<%= form_for(@ship_address) do |f| %>
				<%= render 'shared/error_messages', object: f.object %>
				<%= f.label :region %>
				<%= f.text_field :region %>
				<%= f.label :country %>
				<%= f.country_select :country%>
				<%= f.label :address %>
				<%= f.text_field :address %>
				<%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
				<% end %>
				
			</div>
		</div>

app/views/ship_addresses/show.html.erb
<%= render 'shared/side_bar' %>
	
	<% @user ||= current_user %>
	<div class="center row">
		<h4>Customer Address</h4>
		<aside class="span4 ">
			<table class="table">
				<% ShipAddress.find_each(:conditions => "user_id = #{@user.id}") do |ship| %>
				<tr>
					
					<td>Address:</td><td><%= ship.address %></td>
				</tr>
				<tr>
					<td>Country:</td><td><%= ship.country %></td>
				</tr>
				<tr>
					<td>Region:</td><td><%= ship.region %></td>
				</tr>
				<tr>
					<td colspan="2"><%= link_to 'Edit', edit_address_path , class: "label label-info" %><%= link_to 'Delete', @ship_address, method: :delete,
		data: { confirm: "Are you sure?" }, class: "label label-important" %></td>
				</tr>
				<% end %>
			</table>
			

<%= link_to "Add new ship address", address_path %>
		</aside>			
	</div>
		
</div>