config/routes.rb
CarsonAuto::Application.routes.draw do
  
  root to: 'static_pages#home'
  
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :cars
  resources :users
  resources :ship_addresses
  resources :payment_cards
  resources :carts
  resources :cart_items, only: [:create, :destroy]
  resources :orders
  resources :incoices

  resources :sessions, only: [:new, :create, :destroy]

  match '/addcars', to: 'cars#new'
  
  match '/home', to: 'static_pages#home'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/help', to: 'static_pages#help'

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/edit_user', to: 'users#edit'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/address', to: 'ship_addresses#new'
  match '/ship_address', to: 'ship_addresses#show'
  match '/edit_address', to: 'ship_addresses#edit'
  match '/delete_address', to: 'ship_addresses#destroy'

  match '/new_card', to: 'payment_cards#new'
  match '/credit_card', to: 'payment_cards#show'
  match '/delete_card', to: 'payment_cards#destroy'
  
  match '/add_cart', to: 'carts#create'

  match '/add_cart_item', to: 'cart_items#create'
  match '/show_cart_items', to: 'cart_items#index'
  match '/destroy_cart_item', to: 'cart_items#destroy'
 
  match '/place_order', to: 'orders#create'
  match '/order_history', to: 'orders#show'

  match '/invoice', to: 'invoices#create'

  match '/find_cars', to: 'cars#index'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_side_bar.html.erb
<div class="row">
	<div class="span3">
		<div class="well sidebar-nav">
			<ul class="nav nav-list">
				<li><%= link_to 'Customer Info', current_user %></li>
				<% if ship_address %>
				<li><%= link_to 'Shipping Address', ship_address_path %></li>
				<% else %>
				<li><%= link_to 'Add Shipping Address', address_path %></li>
				<% end %>
				<% if credit_card %>
				<li><%= link_to 'Card Information', credit_card_path %></li>
				<% else %>
				<li><%= link_to 'Add Card information', new_card_path %></li>
				<% end %>
				<li><%= link_to 'Order History', order_history_path %></li>
			</ul>
		</div>
		
	</div>