config/routes.rb
CarsonAuto::Application.routes.draw do
  
  root to: 'static_pages#home'
  
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :cars
  resources :users
  resources :ship_addresses
  resources :payment_cards
  resources :carts
  resources :cart_items, only: [:create, :destroy]
  resources :orders
  resources :incoices

  resources :sessions, only: [:new, :create, :destroy]

  match '/addcars', to: 'cars#new'
  
  match '/home', to: 'static_pages#home'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/help', to: 'static_pages#help'

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/edit_user', to: 'users#edit'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/address', to: 'ship_addresses#new'
  match '/ship_address', to: 'ship_addresses#show'
  match '/edit_address', to: 'ship_addresses#edit'
  match '/delete_address', to: 'ship_addresses#destroy'

  match '/new_card', to: 'payment_cards#new'
  match '/credit_card', to: 'payment_cards#show'
  match '/delete_card', to: 'payment_cards#destroy'
  
  match '/add_cart', to: 'carts#create'

  match '/add_cart_item', to: 'cart_items#create'
  match '/show_cart_items', to: 'cart_items#index'
  match '/destroy_cart_item', to: 'cart_items#destroy'
 
  match '/place_order', to: 'orders#create'
  match '/order_history', to: 'orders#show'

  match '/invoice', to: 'invoices#create'

  match '/find_cars', to: 'cars#index'

end

app/models/car.rb
# == Schema Information
#
# Table name: cars
#
#  id           :integer          not null, primary key
#  make         :string(255)
#  price        :decimal(, )
#  image        :string(255)
#  model        :string(255)
#  year         :integer
#  mileage      :string(255)
#  color        :string(255)
#  transmission :string(255)
#  fuel_type    :string(255)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Car < ActiveRecord::Base
  attr_accessible :color, :fuel_type, :image, :make, :mileage, :model, :price, :transmission, :year, :category, :engine
  mount_uploader :image, ImageUploader
  has_many :invoice_lines
  has_many :carts
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

	def index
		@cars = Car.paginate(page: params[:page], :per_page => 10 ,:conditions => params[:find], :order => 'year DESC')
	end

	def new
		@car = Car.new
	end

	def show
		@car = Car.find(:id)
	end

	def create
		@car =Car.new(params[:car])

		if @car.save
			#show successful save
			flash[:success] = "Successfully added a car"
			redirect_to @car
		else
			render 'new'
		end
	end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_car.html.erb
<div  class="row well">
	<aside class="pull-left">
		<%= image_tag car.image_url(:thumb).to_s, class: "thumbnail" %>
		<b><%= car.make + " " + car.engine + " " %><%= car.model %></b><br>
		<%= link_to 'add to cart', add_cart_item_path(:product => { :product_id => car.id}) %>
	</aside>
					
	<aside class="pull-left span4">		
		<b><%= number_to_currency car.price, :unit => "R" %></b><br>
		<%= car.year %><br>
		<%= car.color %> <br>
		<%= car.mileage + " km" %><br>
		<%= car.transmission %><br>
		<%= car.fuel_type %><br>
	</aside>
</div>

app/views/cars/create.html.erb
<p>
	<%= form_for(@car) do |f| %>
	<%= render 'shared/error_messages' %>

		<%= f.label :make %>
		<%= f.text_field :make %></br>

		<%= f.label :price %>
		<%= f.text_field :price %></br>

		<%= f.label :image_desc %>
		<%= f.text_field :image_desc %></br>

		<%= f.label :image_file %>
		<%= f.file_column_field :image_file %></br>

		<%= f.submit "Upload car info" %>


	<% end %>
</p>

app/views/cars/index.html.erb
<%= provide(:title, 'Cars') %>

<div class="tabbable">	
	<ul class="nav nav-tabs">
		<li><%= link_to "All cars", cars_path , class: "active"%></li>
		<li><%= link_to "Bakkies", find_cars_path(:find => { :category => "bakkie"})%></li>
		<li><%= link_to "Sports cars", find_cars_path(:find => { :category => "sports"}) %></li>
		<li><%= link_to "4x4s", find_cars_path(:find => { :category => "4x4"}) %></li>
		<li><%= link_to "Sedans", find_cars_path(:find => { :category => "sedan"}) %></li>
	</ul>


	
</div>
<div class="row">

	<%= will_paginate %>
		<ul>
			<%= render @cars %>
		</ul>
	<%= will_paginate %>
	
</div>

app/views/cars/new.html.erb
<p>
	<%= form_for(@car, :html => {:multipart => true}) do |f| %>
	<%= render 'shared/error_messages', object: f.object %>

		<%= f.label :make %>
		<%= f.text_field :make %>

		<%= f.label :price %>
		<%= f.text_field :price %>

		<%= f.label :image %>
		<%= f.file_field :image %>

		<%= f.label :model %>
		<%= f.text_field :model %>

		<%= f.label :year %>
		<%= f.text_field :year %>

		<%= f.label :mileage %>
		<%= f.text_field :mileage %>

		<%= f.label :color %>
		<%= f.text_field :color %>

		<%= f.label :transmission %>
		<%= f.text_field :transmission %>

		<%= f.label :fuel_type %>
		<%= f.text_field :fuel_type %>

		<%= f.submit "Upload car info" %>


	<% end %>
</p>

app/views/cars/show.html.erb
<div class="row">
	<%= will_paginate %>
		<%= render @cars %>
	<%= will_paginate %>
</div>