config/routes.rb
CarsonAuto::Application.routes.draw do
  
  root to: 'static_pages#home'
  
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :cars
  resources :users
  resources :ship_addresses
  resources :payment_cards
  resources :carts
  resources :cart_items, only: [:create, :destroy]
  resources :orders
  resources :incoices

  resources :sessions, only: [:new, :create, :destroy]

  match '/addcars', to: 'cars#new'
  
  match '/home', to: 'static_pages#home'
  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/help', to: 'static_pages#help'

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/edit_user', to: 'users#edit'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/address', to: 'ship_addresses#new'
  match '/ship_address', to: 'ship_addresses#show'
  match '/edit_address', to: 'ship_addresses#edit'
  match '/delete_address', to: 'ship_addresses#destroy'

  match '/new_card', to: 'payment_cards#new'
  match '/credit_card', to: 'payment_cards#show'
  match '/delete_card', to: 'payment_cards#destroy'
  
  match '/add_cart', to: 'carts#create'

  match '/add_cart_item', to: 'cart_items#create'
  match '/show_cart_items', to: 'cart_items#index'
  match '/destroy_cart_item', to: 'cart_items#destroy'
 
  match '/place_order', to: 'orders#create'
  match '/order_history', to: 'orders#show'

  match '/invoice', to: 'invoices#create'

  match '/find_cars', to: 'cars#index'

end

app/views/layouts/_footer.html.erb
<footer>

	<small class="center">
		This website is the property of Carson Auto  &copy; 2013 
	</small>

	<nav>
		<ul>
			<li><%= link_to 'About Us', about_path %></li>
			<li><%= link_to 'Help', help_path %></li>
		</ul>
	</nav>
	
	

</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<div class="container">		
		
			<nav>
				<ul class="nav pull-right">
					<li><%= link_to 'Home', root_path  %></li>	
					<li><%= link_to "Cars", cars_path %></li>
					<% if signed_in? %>
						<li id="fat-menu" class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">
							Account <b class="caret"></b>
						</a>
						<ul class="dropdown-menu">
							<li><%= link_to "Profile", current_user %></li>
							<li><%= link_to "Settings", @ship_addresses %></li>
							<li class="divider"></li>
							<li>
								<%= link_to "Sign out", signout_path, method: "delete" %>
							</li>
						</ul>
						</li>
					<% else %>
						<li><%= link_to "Sign in", signin_path %></li>
						<li><%= link_to "Sign up", signup_path %></li>
					<% end %>
				</ul>
			</nav>

		</div>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<% @user ||= current_user %>
	<head>
	  <title>Carson Auto <%= yield(:title) %></title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application", "rails.validations" %>
	  <%= csrf_meta_tags %>
	</head>
	
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<aside class="pull-right"><%= link_to '', show_cart_items_path , class: "icon-shopping-cart" %>(<% if cart? %><%= current_cart.cart_items.count %><%end%>)</aside>
			<% flash.each do |key, value| %>
				<div class="alert alert-<%= key %>"><%= value %></div>
			<% end %>
			<%= yield %>
			<%= render 'layouts/footer'%>
		</div>
	</body>
</html>